version: "2"

services:
  cli:
    build: .
    volumes:
      - ./:/source/:rw
    command: tail -f /dev/null

  test:
    build: .
    volumes:
      - ./:/source/:rw
    command: bash -c 'cargo build; cargo test'
